# data
dataset_name: example # name of dataset: example
datapath: data

# model
model: linear_regression # The model to be used (Now you have: linear_regression, etc...)
checkpoint_dir: save/checkpoints

# train configs
batch_size: 2048 # the batch_size for training or predict, None for not to use batch
learning_rate: 1.0e-4 # initial learning rate for the training model
weight_decay: 1.0e-2 # l2 regularization term for the training model
num_epoch_train: 30000 # The training steps for the training model
load_checkpoint: False # whether loading previous model if it exists
save_checkpoint: False # whether saving the current model
visualize_loss: False # if plot the figure of train loss and test loss

# Individual model configs
model_configs:
  linear_regression:
    None: null